name: Make_OCP_CLI
on:
  push:
    branches:
      - main
    # paths:
    #  - 'ocp-cli/**'
    #  - '.github/workflows/mk-ocp-cli.yml'

env:
  IMAGE: ghcr.io/tomotake-koike/ocp-cli
  OCP_VERSION: "4.13.0"
  
jobs:
  build-image:
    runs-on: ubuntu-latest
    name: Buld OpenShift CLI Container Image
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE }}
          flavor: |
            latest=true
          tags: |
            type=sha,prefix={{date 'YYYYMM'}}-,suffix=,format=short

      - name: Build (and push if on main)
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./ocp-cli
          file: ./ocp-cli/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: VERSION=${{ env.OCP_VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # load: true
          push: ${{ github.ref == 'refs/heads/main' }}

  check-image:
    if: success()
    needs: build-image
    # runs-on: ubuntu-latest
    name: Check OpenShift CLI Container Image
    uses: tomotake-koike/actions-test/.github/workflows/mk-ocp-cli-actions@v1.7
    with:
      image: ${{ env.IMAGE }}:${{ steps.meta.outputs.tags }}
      first-arg: 'version'
        
